
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0' 
target ‘FlowerField’ do 

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYWebImage'
pod 'FMDB'
pod 'ReactiveCocoa', '~> 2.5'

end

