source 'https://github.com/FFComponent/FFSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
platform :ios, '8.0' 
target ‘FlowerField’ do 

pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'Masonry'
pod 'YYWebImage'
pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'

end

